import Headers from '@/components/Headers'
import './globals.css'
import { Inter, Open_Sans } from '@next/font/google'
import { Roboto } from '@next/font/google'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
 weight: '900',
  subsets: ['latin'],
})

const opensans=Open_Sans({
  subsets: ['latin'],
    weight: '700',
})

export const metadata = {
  title: 'Shoes app',
  description: 'Generated by Shoes app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body  className={`${roboto.className} app`} >
        <Headers/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
